### ISSUE TITLE
Would it be worth adding sample nginx config to the readme?

### ISSUE THREAD

**Issue by nicholasjstock** [bitaculous/ember-cli-deploy-rack#1]
Hey, clearly I'm not a sys admin, but I've been struggling with getting all the urls to respond
http://app.com/login returns 404 not found. 

Would it be worth adding a section on configuring nginx for redirects to the readme?

Thanks,

Nick

**Comment by mkempe** [comment]
Hey Nick,

sorry, you hit a bug! With version `2.5.0`, all routes are handled by the Engine. Could you please test the new version and give me feedback.

Thanks,

Maik

**Comment by nicholasjstock** [comment]
Perfect. Upgraded to version 2.5.0, and my current config is fine.
